# Generated by Django 5.1.4 on 2024-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('status', models.IntegerField(null=True, verbose_name='状态')),
                ('login_date', models.DateTimeField(null=True, verbose_name='登录时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=20, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
